#!/sbin/sh
. /tmp/backuptool.functions

list_files() {
cat <<EOF
addon.d/80-gapps.sh
addon.d/71-gapps-faceunlock.sh
app/FaceLock/FaceLock.apk
etc/permissions/com.google.android.camera2.xml
framework/com.google.android.camera2.jar
lib/libgcam.so
lib/libgcam_swig_jni.so
lib/libjni_eglfence.so
lib/libjni_filtershow_filters.so
lib/libjni_mosaic.so
lib/liblightcycle.so
lib/libnativehelper_compat.so
app/Books/Books.apk
app/CalendarGoogle/CalendarGoogle.apk
app/CameraGoogle/CameraGoogle.apk
app/Chrome/Chrome.apk
app/CloudPrint/CloudPrint.apk
app/ConfigUpdater/ConfigUpdater.apk
app/Docs/Docs.apk
app/Drive/Drive.apk
app/ExchangeServices/ExchangeServices.apk
app/Games/Games.apk
app/GenieWidget/GenieWidget.apk
app/Gmail2/Gmail2.apk
app/GoogleCalendarSyncAdapter/GoogleCalendarSyncAdapter.apk
app/GoogleContactsSyncAdapter/GoogleContactsSyncAdapter.apk
app/GoogleHome/GoogleHome.apk
app/GoogleTTS/GoogleTTS.apk
app/Hangouts/Hangouts.apk
app/HangoutsDialer/HangoutsDialer.apk
app/Keep/Keep.apk
app/Keyboard/Keyboard.apk
app/Maps/Maps.apk
app/Messenger/Messenger.apk
app/Movies/Movies.apk
app/Music2/Music2.apk
app/Newsstand/Newsstand.apk
app/PlusOne/PlusOne.apk
app/Sheets/Sheets.apk
app/Slides/Slides.apk
app/Street/Street.apk
app/Translate/Translate.apk
app/Wallet/Wallet.apk
app/YouTube/YouTube.apk
etc/g.prop
etc/permissions/com.google.android.camera2.xml
etc/permissions/com.google.android.dialer.support.xml
etc/permissions/com.google.android.maps.xml
etc/permissions/com.google.android.media.effects.xml
etc/permissions/com.google.widevine.software.drm.xml
etc/permissions/features.xml
etc/preferred-apps/google.xml
framework/com.google.android.camera2.jar
framework/com.google.android.dialer.support.jar
framework/com.google.android.maps.jar
framework/com.google.android.media.effects.jar
framework/com.google.widevine.software.drm.jar
lib/libfilterpack_facedetect.so
lib/libjni_latinime.so
lib/libjni_latinimegoogle.so
priv-app/GoogleBackupTransport/GoogleBackupTransport.apk
priv-app/GoogleFeedback/GoogleFeedback.apk
priv-app/GoogleLoginService/GoogleLoginService.apk
priv-app/GoogleOneTimeInitializer/GoogleOneTimeInitializer.apk
priv-app/GooglePartnerSetup/GooglePartnerSetup.apk
priv-app/GoogleServicesFramework/GoogleServicesFramework.apk
priv-app/Phonesky/Phonesky.apk
priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk
priv-app/SetupWizard/SetupWizard.apk
priv-app/Velvet/Velvet.apk
priv-app/talkback/talkback.apk
tts/lang_pico/de-DE_gl0_sg.bin
tts/lang_pico/de-DE_ta.bin
tts/lang_pico/es-ES_ta.bin
tts/lang_pico/es-ES_zl0_sg.bin
tts/lang_pico/fr-FR_nk0_sg.bin
tts/lang_pico/fr-FR_ta.bin
tts/lang_pico/it-IT_cm0_sg.bin
tts/lang_pico/it-IT_ta.bin
usr/srec/en-US/commands.abnf
usr/srec/en-US/compile_grammar.config
usr/srec/en-US/contacts.abnf
usr/srec/en-US/dictation.config
usr/srec/en-US/endpointer_dictation.config
usr/srec/en-US/endpointer_voicesearch.config
usr/srec/en-US/grammar.config
usr/srec/en-US/hotword.config
usr/srec/en-US/hotword_prompt.txt
vendor/pittpatt
EOF
}

list_files | while read FILE DUMMY; do
      delete_file $S/$FILE
done

